### ISSUE TITLE
Website Roadmap 

### ISSUE THREAD

**Issue by orta** [microsoft/TypeScript-Website#94]
If you'd like to see and know more about the website infrastructure, there is [an "updates thread"](https://github.com/microsoft/TypeScript-Website/issues/130) which digs into both what has been happening, and why.

My roadmap for the site + branding, influenced strongly by community feedback in  https://github.com/microsoft/TypeScript/issues/31983. Presented, roughly, as a linear priority list but in reality quite a lot are interlinked and so are being worked on concurrently. 

- [x] New Index Page 
- [x] Replacement for intermediary pages (samples etc)
- [x] New Handbook Design
- [x] New Playground v3
- [x] Dark Mode
- [x] TSConfig Reference
- [x] Internationalization ([roughly](https://github.com/microsoft/TypeScript-Website/issues/100))
- [x] Branding Page
- [x] Search
- [x] Mobile nav
- [x] a11y audit

### New Logo

[Embrace the community logo](https://github.com/remojansen/logo.ts) by creating an official logo influenced by that version with some minor design tweaks.

![Screen Shot 2019-10-23 at 10 51 53 AM](https://user-images.githubusercontent.com/49038/67405738-2ada9600-f583-11e9-9bcd-08fe1fe91ba4.png)
[Figma](https://www.figma.com/file/hCZSxoL1rbJxX3Ua3kGNKB/ts-design-spec?node-id=0%3A1)

This logo is then used throughout the re-designs below, and important for the branding page. We can provide official resources then ( see branding page at the bottom )

### ~~Re-designed Docs pages~~

![Screen Shot 2019-10-23 at 10 39 42 AM](https://user-images.githubusercontent.com/49038/67404478-768c4000-f581-11e9-8b2e-85a1468c3263.png)
[Figma](https://www.figma.com/file/x8FJrNqj6oupqWn1s3uMg4/Website?node-id=7%3A0)

- Brings it more in line with docs.microsoft.com 
- [Utilise the TypeScript compiler for error messaging and introspection](https://github.com/microsoft/TypeScript-Website/issues/120)
- Improve the navigation both in-page and for sections like the handbook
- Support switching code samples into playground sandboxes
- Design offers some useful extras:
 - Shows contributors to the page, which should provide some incentive for more authors
 - Shows when it was last updated

### Redesigned Index page

![Screen Shot 2019-10-23 at 10 11 32 AM](https://user-images.githubusercontent.com/49038/67401695-82760300-f57d-11e9-9c69-93643cde2edb.png)
[Figma](https://www.figma.com/file/x8FJrNqj6oupqWn1s3uMg4/Website?node-id=4%3A54)

Aimed at:

- simplifying TypeScript's messaging, making it easier for non-technical people to grok
- emphasize scope of DTS and how TS powers a lot of editor support for JS 
- provide mode jump off points to docs, and understanding of TS release schedules
- showcasing work in TC39
- updating testamonials
- highlighting more talks from TS core team
- Have a design aesthetic which is closer to Microsoft's fluid UI system
- de-empathise the spec, given it's lack of updates

### ~~Add search to the site~~  🎉 Done

Super highly requested, algolia have reached out and will [provide DocSearch](https://community.algolia.com/docsearch/) for free over existing TS site as they do for other large OSS JS sites. I've worked with them before and it's been 👍 

![Screen Shot 2019-10-23 at 10 45 41 AM](https://user-images.githubusercontent.com/49038/67405077-45f8d600-f582-11e9-8afc-bfd629a68f55.png)

### Fix some DNS issues

- You _have_ to use `www.` today, that's a shame
- `http` links should be redirect to `https` to stop people thinking we've mis-configured the site
- Maybe a smaller link for playground URLs?

### ~~TSConfig Tooling~~

![Screen Shot 2019-11-01 at 11 37 47 AM](https://user-images.githubusercontent.com/49038/68036849-df1f9f00-fc9c-11e9-9ad6-38363c99d704.png)

- Build a page which consolidates all docs on the TSConfig, maybe a playground-like experience as well as a full linkable reference. [tsconfig-ui](https://github.com/MatterhornDev/tsconfig-ui) might be a good place for exploration there. See https://github.com/microsoft/TypeScript-Website/pull/103 for WIP
- Have sample TSConfigs for particular type of libraries
- Provide more extensive documentation about each flag inside the compiler, this can come from [the new handbook too](https://github.com/microsoft/TypeScript-New-Handbook/blob/master/reference/Compiler%20Options.md)

### I18n

Add support for non-English documentation https://github.com/microsoft/TypeScript-Website/issues/100

### CLI Docs
- Re-examine `tsc --help` because:
  - Not all compiler flags are in there
  - It should probably link to this resource

### Community Section

#5 has a lot of context  for this

- Encourage more people connect offline
- Provide "blessing" for resources to have a more consistent way to have the community help each other
- Give ownership of sections to people who want to do work in the community
- Highlight books, mailing lists etc which lets people learn in alternative ways

### ~~Dark Mode for docs + playground~~

I'm getting daily pings about this, in part because it's become a meme but I think all popular consumer OS' now support light/dark modes and there's https://github.com/microsoft/TypeScript-Website/issues/90

Likely to come in with the redesigned pages.

### ~~Allow community localizations~~

Two big OSS JS sites have been doing community translations of content (react and Gatsby) and we can reuse their infra and ideas -  https://github.com/gatsbyjs/rfcs/pull/42

We can use tools like [code-organizer-merge-on-green](https://github.com/orta/code-organizer-merge-on-green) to allow others to handle merging PRs to languages they know

### Convert from "everything in the handbook" to site sub-sections

![Screen Shot 2019-10-23 at 10 38 22 AM](https://user-images.githubusercontent.com/49038/67404354-42188400-f581-11e9-9a54-3b54c8391817.png)
[Figma](https://www.figma.com/file/Sew0DK1pRVPVXF6aAarfQHjk/Sitemap?node-id=0%3A1)

Today almost all information about TypeScript lives in the handbook, ideally that would only be the language reference. We can kill the submodule and migrate it into the site (now that the site is OSS).

With sub-sections things like:

 - Using JSDoc for Types
 - Migrating from JS to TS
 - Migrating from TS to TS Strict
 - Working with Definitely Typed
 - Using Projects to split up big repos
 - Using TypeScript with build tools
 - Shipping a JS Library with types
 - React + TypeScript (it's one of the biggest TS eco-systems where they have little to official docs on how they work together)

We can also give ownership of some of these areas to contributors using [code-organizer-merge-on-green](https://github.com/orta/code-organizer-merge-on-green)

### Better Resources for Compiler API users

- Audit existing documentation in the wiki
- Add JSDoc comments to anything missing them in the public interface
- Provide a full API reference via [api-extractor](https://api-extractor.com) https://github.com/microsoft/TypeScript-Website/issues/80
- Maybe move resources into a sub-section on the site

### Explore an interactive guide to basic + advanced types

The two pages [Basic Types](https://www.typescriptlang.org/docs/handbook/basic-types.html) and [Advanced Types](https://www.typescriptlang.org/docs/handbook/advanced-types.html) represent a quarter of all traffic. Can we make something that consolidates the two, but isn't so dense?

### Work to ensure multiple explanations of TypeScript concepts

We often describe concepts in terms of each other, and sometimes very technically, which can be tough for some learners. 

- Provide playground example alternatives to intermediate and advanced type ideas
- Provide a glossary of TypeScript terms

### Re-designed Playground

I added a lot of the features from the re-design in the current v2 of the playground, so it's mostly a design change now. But the revised sidebar would be nice. There's also [~20 open issues on the playground](https://github.com/microsoft/TypeScript-Website/issues?q=is%3Aissue+is%3Aopen+label%3APlayground) this would be a good time to hit some of those.

![Screen Shot 2019-10-23 at 10 11 58 AM](https://user-images.githubusercontent.com/49038/67401739-902b8880-f57d-11e9-9e7c-a4f523300623.png)
[Figma](https://www.figma.com/file/Q0872II3wi1EzCXV9eUNBqb7/Playground?node-id=5%3A10)

### ~~Split Playground into Playground + Sandbox~~

> The TypeScript Sandbox is the editor part of the TypeScript Playground. It's effectively an opinionated fork of monaco-typescript with extra extension points so that projects like the TypeScript Playground can exist.

[WIP build](https://github.com/microsoft/TypeScript-Website/tree/v2/packages/sandbox)

This would allow us to embed the monaco-editor with a lot of playground features into documentation pages on request, as well as allowing external parties to have their own TypeScript powered API references with DTS files trivially.

Represents the end of the [typescript-play](https://github.com/orta/typescript-play) fork.

### New Branding Page

- [Similar to Discord's](https://discordapp.com/branding) in theme, provides all the logos and some light recommendations on how to use the logo.

- [Gatsby's](https://www.gatsbyjs.org/guidelines/logo/) is good also 

- Can provide recommendations for how folks can make and print their own stickers

**Comment by Draem** [comment]
Epic.

**Comment by IgorHalfeld** [comment]
Awesome!!

**Comment by orta** [comment]
I shipped the branding page today, which makes this 100% done on the current roadmap.

**Comment by orta** [comment]
Done and shipped.
